import type { NextConfig } from "next";

const permanentRedirects = [
  { source: "/about-sailor-bar", destination: "/about", permanent: true },
  { source: "/recreation", destination: "/about", permanent: true },
  { source: "/amenities", destination: "/about", permanent: true },
  { source: "/friends-of-sailor-bar-brochure-and-map", destination: "/about", permanent: true },
  { source: "/turtle-pond", destination: "/about/turtle-pond", permanent: true },
  { source: "/boat-launch", destination: "/about/boat-launch", permanent: true },
  { source: "/olive-avenue-river-overlook", destination: "/about/olive-avenue-overlook", permanent: true },
  { source: "/aerojet-groundwater-pumps", destination: "/about/aerojet-groundwater-pumps", permanent: true },
  { source: "/grinding-rocks", destination: "/about/grinding-rocks", permanent: true },
  { source: "/heron-rookeries", destination: "/about/heron-rookeries", permanent: true },
  { source: "/flag-pole", destination: "/about/flag-pole", permanent: true },
  { source: "/our-aspiration", destination: "/friends-of-sailor-bar", permanent: true },
  { source: "/get-involved", destination: "/volunteer", permanent: true },
  { source: "/your-donations-support-sailor-bar-activities", destination: "/donate", permanent: true },
  { source: "/plant-life", destination: "/wildlife/plant-life", permanent: true },
  { source: "/interactive-birding-at-sailor-bar/birding-at-sailor-bar", destination: "/wildlife/birding", permanent: true },
  { source: "/nature-study", destination: "/wildlife/salmon-and-steelhead", permanent: true },
  { source: "/the-elderberry", destination: "/wildlife/elderberry", permanent: true },
  { source: "/great-horned-owl-nest-east-of-sailor-bar", destination: "/wildlife/great-horned-owls", permanent: true },
  { source: "/a-detailed-history-of-sailor-bar", destination: "/history", permanent: true },
  { source: "/native-american-history", destination: "/history/nisenan-history", permanent: true },
  { source: "/gold-dredging-industrial-mining-on-a-massive-scale", destination: "/history/mining-and-dredging", permanent: true },
  { source: "/chinese-diggings-across-from-sailor-bar", destination: "/history/chinese-diggings", permanent: true },
  { source: "/859-2", destination: "/history/river-changes", permanent: true },
  { source: "/remembering-camp-sabadaca", destination: "/history/camp-sabadaca", permanent: true },
  { source: "/sailor-bar-history", destination: "/history/gold-rush-legacy", permanent: true },
  { source: "/the-ghost-of-sailor-bar", destination: "/history/the-ghost-of-sailor-bar", permanent: true },
  { source: "/partners-affiliates", destination: "/partners", permanent: true },
  { source: "/american-river-parway-bike-patrol", destination: "/partners/american-river-bike-patrol", permanent: true },
  { source: "/american-river-parkway-equestrian-patrol", destination: "/partners/american-river-parkway-equestrian-patrol", permanent: true },
  { source: "/fair-oaks-historical-society", destination: "/partners/fair-oaks-historical-society", permanent: true },
  { source: "/friends-of-lakes-folsom-and-natoma-folfan", destination: "/partners/friends-of-lakes-folsom-and-natoma-folfan", permanent: true },
  { source: "/project-pick-up-fishing-line", destination: "/partners/project-pick-up-fishing-line", permanent: true },
  { source: "/river-city-waterway-alliance", destination: "/partners/river-city-waterway-alliance", permanent: true },
  { source: "/sacramento-bird-alliance", destination: "/partners/sacramento-bird-alliance", permanent: true },
  { source: "/sacramento-county-regional-parks", destination: "/partners/sacramento-county-regional-parks", permanent: true },
  { source: "/save-the-american-river-association-sara", destination: "/partners/save-the-american-river-association", permanent: true },
  { source: "/waterbird-habitat", destination: "/partners/waterbird-habitat-project", permanent: true },
  { source: "/sacramento-water-forum", destination: "/stories/water-forum-2050-agreement", permanent: true },
  { source: "/side-channel", destination: "/stories/restoring-room-young-salmon", permanent: true },
  { source: "/friends-of-sailor-bar-rock-off-on-october-3rd-2025", destination: "/events/friends-of-sailor-bar-rock-off", permanent: true },
  { source: "/sailor-bar-bench-and-table-dedication-ceremony", destination: "/events/bench-and-table-dedication", permanent: true },
  { source: "/sailor-bar-bench-dedication", destination: "/events/bench-and-table-dedication", permanent: true },
  { source: "/earth-day-april-2026", destination: "/events/earth-day-at-sailor-bar-2026", permanent: true },
  { source: "/interactive-birding-at-sailor-bar", destination: "/events/interactive-birding-2026", permanent: true },
  { source: "/health-wellness-day", destination: "/events/family-health-and-wellness-day-2026", permanent: true },
  { source: "/celebrating-american-river-parkway-heroes", destination: "/events/american-river-parkway-heroes-2026", permanent: true },
  { source: "/the-wild-and-scenic-american-river", destination: "/events/wild-and-scenic-american-river-2026", permanent: true },
  { source: "/event/bald-eagles-and-birdhouses", destination: "/events/real-wildlife-encounters", permanent: true },
  { source: "/real-wildlife-encounters", destination: "/events/real-wildlife-encounters", permanent: true },
  { source: "/the-ghost-of-sailor-bar-how-sailor-bar-got-its-name-legends-and-historical-facts", destination: "/events/ghost-of-sailor-bar", permanent: true },
  { source: "/something-fishy-is-going-on-here-the-remarkable-spawning-journey", destination: "/events/salmon-spawning-journey", permanent: true },
  { source: "/event-calendar", destination: "/events", permanent: true },
] satisfies NonNullable<Awaited<ReturnType<NonNullable<NextConfig["redirects"]>>>>;

const nextConfig: NextConfig = {
  allowedDevOrigins: ["sailorbar.exe.xyz", "sailorbar.exe.xyz:8000"],
  async redirects() {
    return permanentRedirects;
  },
};

export default nextConfig;
